#' @title Clean the occurrence records
#' @name clean
#'
#' @description A function to remove the points that are outside the extension of the raster and to maintain, at most one register per pixel.
#'
#' @param occurrences data.frame with the coordinates
#' @param predictors an object with the rasters to be cut. Accepts an object of type RasterStack, generated by the function \code{\link[raster]{stack}}
#'
#' @details Used internally in function \code{\link[modelos]{modelos}}.
#'
#' @return data.frame containing longitude and latitude.
#'
#' @author Diogo S. B. Rocha
#'
#' @seealso \code{\link[raster]{cellFromXY}}, \code{\link[raster]{mask}}, \code{\link[raster]{extract}}
#'
#' @examples
#' predictors <- example_vars
#' clean(occurrences = coordenas[,-1], predictors = predictors)
#'
#' @import raster
#'
#' @export
clean = function(occurrences, predictors, clean_dupl = TRUE, clean_nas = TRUE, clean_uni = TRUE) { #coord ; abio
    if (dim(occurrences)[2] == 2) {
        if (exists("predictors")) {

          # tabela de valores
          message("extracting environmental data")
          presvals <- raster::extract(predictors, occurrences)
          if (clean_dupl == TRUE) {
            message("cleaning duplicates")
            dupls <- !base::duplicated(occurrences)
            occurrences <- occurrences[dupls,]
            presvals <- presvals[dupls,]
          }
          if (clean_nas == TRUE) {
            message("cleaning occurrences with no environmental data")
            compl <- complete.cases(presvals)
            occurrences <- occurrences[compl,]
            presvals <- presvals[compl,]
          }

          if (clean_nas == TRUE) {
            # selecionar os pontos únicos e sem NA
            mask = predictors[[1]]
            # Selecionar pontos espacialmente únicos #
            cell <- cellFromXY(mask, occurrences)  # get the cell number for each point
            dup <- duplicated(cell)
            pts1 <- occurrences[!dup, ]  # select the records that are not duplicated
            pts1 <- pts1[!is.na(extract(mask, pts1)), ]  #selecionando apenas pontos que tem valor de raster
            }

            cat(dim(occurrences)[1] - dim(pts1)[1], "points removed\n")
            cat(dim(pts1)[1], "spatially unique points\n")
            names(pts1) = c("lon", "lat")#
            return(pts1)
        } else (cat("Indicate the object with the predictive variables"))
    } else (stop("Coordinate table has more than two columns.\nThis table should only have longitude and latitude in this order."))
}
