#' @title Clean the occurrence records
#' @name clean
#'
#' @description A function to remove the points that are outside the extension of the raster and to maintain, at most one register per pixel.
#'
#' @param occurrences data.frame with the coordinates
#' @param predictors an object with the rasters to be cut. Accepts an object of type RasterStack, generated by the function \code{\link[raster]{stack}}
#' @param clean_dupl logical. If TURE removes points with the same longitude and latitude
#' @param clean_nas logical. If TURE removes points that are outside the bounds of the raster
#' @param clean_uni logical. If TURE selects only one point per pixel
#'
#' @details Used internally in function \code{\link[ModelR]{setup_sdmdata}}.
#'
#' @return data.frame containing longitude and latitude.
#'
#' @author Diogo S. B. Rocha
#'
#' @seealso \code{\link[raster]{cellFromXY}}, \code{\link[raster]{mask}}, \code{\link[raster]{extract}}
#'
#' @examples
#' sp <- unique(coordenadas$sp)[1]
#' sp.coord <- coordenadas[coordenadas$sp == sp,-1]
#' clean(occurrences = sp.coord, predictors = example_vars)
#'
#' @import raster
#'
#' @export
clean = function(occurrences, predictors, clean_dupl = TRUE, clean_nas = TRUE, clean_uni = TRUE) {
    if (dim(occurrences)[2] == 2) {
        if (exists("predictors")) {
          ori <- dim(occurrences)[1]
          if (clean_dupl == TRUE) {
            message("cleaning duplicates")
            dupls <- !base::duplicated(occurrences)
            occurrences <- occurrences[dupls,]
          }
          if (clean_nas == TRUE) {
            message("cleaning occurrences with no environmental data")
            presvals <- raster::extract(predictors, occurrences)
            compl <- complete.cases(presvals)
            occurrences <- occurrences[compl,]
          }

          if (clean_uni == TRUE) {
            if(clean_nas == FALSE){warning("There may be points that are outside the raster")}
            mask = predictors[[1]]
            cell <- cellFromXY(mask, occurrences)
            dup <- duplicated(cell)
            occurrences <- occurrences[!dup, ]
            }

            cat(ori - dim(occurrences)[1], "points removed\n")
            cat(dim(occurrences)[1], " clean points\n")
            #names(occurrences) = c("lon", "lat")
            return(occurrences)
        } else (cat("Indicate the object with the predictive variables"))
    } else (stop("Coordinate table has more than two columns.\nThis table should only have longitude and latitude in this order."))
}
