#' Fits ecological niche models for various algorithms.
#'
#' @inheritParams do_any
#' @param bioclim Execute bioclim from the dismo implementation
#' @param domain Execute domain from the dismo implementation
#' @param mahal Execute mahalanobis distance from the dismo implementation
#' @param maxent Execute maxent from the dismo implementation
#' @param glm Execute GLM as suggested by the dismo documentation
#' @param rf Execute random forests from randomForest() as suggested
#' by the dismo documentation
#' @param svm.k Execute svm from kernlab package
#' @param svm.e Execute svm from e1071 package
#' @return A set of ecological niche models for each partition and algorithm,
#'         written in the \code{models_dir} subfolder
#' @author Andrea Sánchez-Tapia
#' @export
#'
do_enm <- function(species_name,
                   coordinates,
                   # lon = "lon",
                   # lat = "lat",
                   # real_absences = NULL,
                   # buffer = FALSE,
                   # seed = 512,
                   predictors,
                   # clean_nas = F,
                   models_dir = "./models",
                   # project_model = FALSE,
                   # projections = NULL,
                   # mask = NULL,
                   # write_png = FALSE,
                   # n_back,
                   # bootstrap = F,
                   # boot_proportion = 0.8,
                   # boot_n = 10,
                   # crossvalidation = F,
                   # cv_partitions,
                   # cv_n = 1,
                   # plot_sdmdata = TRUE,
                   bioclim = FALSE,
                   domain = FALSE,
                   glm = FALSE,
                   mahal = FALSE,
                   maxent = FALSE,
                   rf = FALSE,
                   svm.k = FALSE,
                   svm.e = FALSE,
                   ...) {

    if (bioclim == T) {
        do_any(
            species_name,
            algo = "bioclim",
            coordinates = coordinates,
            # lon = lon,
            # lat = lat,
            # real_absences = real_absences,
            # buffer = buffer,
            # seed = seed,
            predictors = predictors,
            # clean_nas = clean_nas,
            models_dir = models_dir,
            # project_model = project_model,
            # projections = projections,
            # mask = mask,
            #write_png = write_png,
            # n_back = n_back,
            # bootstrap = bootstrap,
            # boot_proportion = boot_proportion,
            # boot_n = boot_n,
            # crossvalidation = crossvalidation,
            # cv_partitions = cv_partitions,
            # cv_n = cv_n,
            # plot_sdmdata = plot_sdmdata,
            ...)
    }
    if (domain == T) {
        do_any(
            species_name,
            algo = "domain",
            coordinates = coordinates,
            #lon = lon,
            #lat = lat,
            # real_absences = real_absences,
            # buffer = buffer,
            # seed = seed,
            predictors = predictors,
            # clean_nas = clean_nas,
            models_dir = models_dir,
            # project_model = project_model,
            # projections = projections,
            # mask = mask,
            # write_png = write_png,
            # n_back = n_back,
            # bootstrap = bootstrap,
            # boot_proportion = boot_proportion,
            # boot_n = boot_n,
            # crossvalidation = crossvalidation,
            # cv_partitions = cv_partitions,
            # cv_n = cv_n,
            # plot_sdmdata = plot_sdmdata,
            ...)
    }
    if (glm == T) {
        do_any(
            species_name,
            algo = "glm",
            coordinates = coordinates,
            # lon = lon,
            # lat = lat,
            # real_absences = real_absences,
            # buffer = buffer,
            # seed = seed,
            predictors = predictors,
            # clean_nas = clean_nas,
            models_dir = models_dir,
            # project_model = project_model,
            # projections = projections,
            # mask = mask,
            # write_png = write_png,
            # n_back = n_back,
            # bootstrap = bootstrap,
            # boot_proportion = boot_proportion,
            # boot_n = boot_n,
            # crossvalidation = crossvalidation,
            # cv_partitions = cv_partitions,
            # cv_n = cv_n,
            # plot_sdmdata = plot_sdmdata,
            ...)
    }
    if (mahal == T) {
        do_any(
            species_name,
            algo = "mahal",
            coordinates = coordinates,
            # lon = lon,
            # lat = lat,
            # real_absences = real_absences,
            # buffer = buffer,
            # seed = seed,
            predictors = predictors,
            # clean_nas = clean_nas,
            models_dir = models_dir,
            # project_model = project_model,
            # projections = projections,
            # mask = mask,
            # write_png = write_png,
            # n_back = n_back,
            # bootstrap = bootstrap,
            # boot_proportion = boot_proportion,
            # boot_n = boot_n,
            # crossvalidation = crossvalidation,
            # cv_partitions = cv_partitions,
            # cv_n = cv_n,
            # plot_sdmdata = plot_sdmdata,
            ...)
    }
    if (maxent == T) {
        do_any(
            species_name,
            algo = "maxent",
            coordinates = coordinates,
            # lon = lon,
            # lat = lat,
            # real_absences = real_absences,
            # buffer = buffer,
            # seed = seed,
            predictors = predictors,
            # clean_nas = clean_nas,
            models_dir = models_dir,
            # project_model = project_model,
            # projections = projections,
            # mask = mask,
            # write_png = write_png,
            # n_back = n_back,
            # bootstrap = bootstrap,
            # boot_proportion = boot_proportion,
            # boot_n = boot_n,
            # crossvalidation = crossvalidation,
            # cv_partitions = cv_partitions,
            # cv_n = cv_n,
            # plot_sdmdata = plot_sdmdata,
            ...)
    }
    if (rf == T) {
        do_any(
            species_name,
            algo = "rf",
            coordinates = coordinates,
            # lon = lon,
            # lat = lat,
            # real_absences = real_absences,
            # buffer = buffer,
            # seed = seed,
            predictors = predictors,
            # clean_nas = clean_nas,
            models_dir = models_dir,
            # project_model = project_model,
            # projections = projections,
            # mask = mask,
            # write_png = write_png,
            # n_back = n_back,
            # bootstrap = bootstrap,
            # boot_proportion = boot_proportion,
            # boot_n = boot_n,
            # crossvalidation = crossvalidation,
            # cv_partitions = cv_partitions,
            # cv_n = cv_n,
            # plot_sdmdata = plot_sdmdata,
            ...)
    }
    if (svm.k == T) {
        do_any(
            species_name,
            algo = "svm.k",
            coordinates = coordinates,
            # lon = lon,
            # lat = lat,
            # real_absences = real_absences,
            # buffer = buffer,
            # seed = seed,
            predictors = predictors,
            # clean_nas = clean_nas,
            models_dir = models_dir,
            # project_model = project_model,
            # projections = projections,
            # mask = mask,
            # write_png = write_png,
            # n_back = n_back,
            # bootstrap = bootstrap,
            # boot_proportion = boot_proportion,
            # boot_n = boot_n,
            # crossvalidation = crossvalidation,
            # cv_partitions = cv_partitions,
            # cv_n = cv_n,
            # plot_sdmdata = plot_sdmdata,
            ...)
    }
    if (svm.e == T) {
        do_any(
            species_name,
            algo = "svm.e",
            coordinates = coordinates,
            # lon = lon,
            # lat = lat,
            # real_absences = real_absences,
            # buffer = buffer,
            # seed = seed,
            predictors = predictors,
            # clean_nas = clean_nas,
            models_dir = models_dir,
            # project_model = project_model,
            # projections = projections,
            # mask = mask,
            # write_png = write_png,
            # n_back = n_back,
            # bootstrap = bootstrap,
            # boot_proportion = boot_proportion,
            # boot_n = boot_n,
            # crossvalidation = crossvalidation,
            # cv_partitions = cv_partitions,
            # cv_n = cv_n,
            # plot_sdmdata = plot_sdmdata,
            ...)
    }
}
